///////////////////////////////////////////////////////////////////////////////
// teapot.h
// ========
// vertex, normal and index array for teapot model
// (6320 polygons, 3241 vertices, 3259 normals)
//
//  AUTHOR: Song Ho Ahn (song.ahn@gmail.com)
// CREATED: 2005-10-05
// UPDATED: 2005-10-05
//
// 3D model is converted by the PolyTrans from Okino Computer Graphics, Inc.
//
// Bounding box of geometry = (-3,0,-2) to (3.434,3.15,2).
///////////////////////////////////////////////////////////////////////////////

unit oglTeapot;

{$mode objfpc}{$H+}

interface

uses
  Classes, SysUtils, gl, oglTypes;

// Draw teapot using absolute pointers to indexed vertex array.
procedure DrawTeapot;

// Create a display list for teapot
function CreateTeapotDL: GLuint;


implementation

{$I oglteapot_vertices.inc}

const
  Shininess: GLfloat = 15.0;
  DiffuseColor: ToglVector3f = (0.929524, 0.796542, 0.178823);
  SpecularColor: ToglVector4f = (1.00000, 0.980392, 0.549020, 1.0);

{-------------------------------------------------------------------------------
  Draw teapot using absolute pointers to indexed vertex array.
-------------------------------------------------------------------------------}
procedure DrawTeapot;
begin
  // set specular and shiniess using glMaterial (gold-yellow)
  glMaterialf(GL_FRONT_AND_BACK, GL_SHININESS, Shininess); // range 0 ~ 128
  glMaterialfv(GL_FRONT_AND_BACK, GL_SPECULAR, SpecularColor);

  // set ambient and diffuse color using glColorMaterial (gold-yellow)
  glColorMaterial(GL_FRONT_AND_BACK, GL_AMBIENT_AND_DIFFUSE);
  glColor3fv(DiffuseColor);

  // start to render polygons
  glEnableClientState(GL_NORMAL_ARRAY);
  glEnableClientState(GL_VERTEX_ARRAY);

  glNormalPointer(GL_FLOAT, 0, @TEAPOT_NORMALS);
  glVertexPointer(3, GL_FLOAT, 0, @TEAPOT_VERTICES);

  glDrawElements(GL_TRIANGLE_STRIP, 12, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[0]);
  glDrawElements(GL_TRIANGLE_STRIP, 78, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[12]);
  glDrawElements(GL_TRIANGLE_STRIP, 35, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[90]);
  glDrawElements(GL_TRIANGLE_STRIP, 70, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[125]);
  glDrawElements(GL_TRIANGLE_STRIP, 65, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[195]);
  glDrawElements(GL_TRIANGLE_STRIP, 37, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[260]);
  glDrawElements(GL_TRIANGLE_STRIP, 35, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[297]);
  glDrawElements(GL_TRIANGLE_STRIP, 32, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[332]);
  glDrawElements(GL_TRIANGLE_STRIP, 56, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[364]);
  glDrawElements(GL_TRIANGLE_STRIP, 45, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[420]);
  glDrawElements(GL_TRIANGLE_STRIP, 41, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[465]);
  glDrawElements(GL_TRIANGLE_STRIP, 37, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[506]);
  glDrawElements(GL_TRIANGLE_STRIP, 33, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[543]);
  glDrawElements(GL_TRIANGLE_STRIP, 29, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[576]);
  glDrawElements(GL_TRIANGLE_STRIP, 25, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[605]);
  glDrawElements(GL_TRIANGLE_STRIP, 21, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[630]);
  glDrawElements(GL_TRIANGLE_STRIP, 17, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[651]);
  glDrawElements(GL_TRIANGLE_STRIP, 13, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[668]);
  glDrawElements(GL_TRIANGLE_STRIP, 9, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[681]);
  glDrawElements(GL_TRIANGLE_STRIP, 27, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[690]);
  glDrawElements(GL_TRIANGLE_STRIP, 16, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[717]);
  glDrawElements(GL_TRIANGLE_STRIP, 22, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[733]);
  glDrawElements(GL_TRIANGLE_STRIP, 50, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[755]);
  glDrawElements(GL_TRIANGLE_STRIP, 42, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[805]);
  glDrawElements(GL_TRIANGLE_STRIP, 43, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[847]);
  glDrawElements(GL_TRIANGLE_STRIP, 4, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[890]);
  glDrawElements(GL_TRIANGLE_STRIP, 143, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[894]);
  glDrawElements(GL_TRIANGLE_STRIP, 234, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[1037]);
  glDrawElements(GL_TRIANGLE_STRIP, 224, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[1271]);
  glDrawElements(GL_TRIANGLE_STRIP, 71, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[1495]);
  glDrawElements(GL_TRIANGLE_STRIP, 69, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[1566]);
  glDrawElements(GL_TRIANGLE_STRIP, 67, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[1635]);
  glDrawElements(GL_TRIANGLE_STRIP, 65, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[1702]);
  glDrawElements(GL_TRIANGLE_STRIP, 63, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[1767]);
  glDrawElements(GL_TRIANGLE_STRIP, 61, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[1830]);
  glDrawElements(GL_TRIANGLE_STRIP, 59, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[1891]);
  glDrawElements(GL_TRIANGLE_STRIP, 57, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[1950]);
  glDrawElements(GL_TRIANGLE_STRIP, 55, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[2007]);
  glDrawElements(GL_TRIANGLE_STRIP, 53, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[2062]);
  glDrawElements(GL_TRIANGLE_STRIP, 51, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[2115]);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[2166]);
  glDrawElements(GL_TRIANGLE_STRIP, 50, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[2169]);
  glDrawElements(GL_TRIANGLE_STRIP, 48, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[2219]);
  glDrawElements(GL_TRIANGLE_STRIP, 46, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[2267]);
  glDrawElements(GL_TRIANGLE_STRIP, 44, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[2313]);
  glDrawElements(GL_TRIANGLE_STRIP, 42, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[2357]);
  glDrawElements(GL_TRIANGLE_STRIP, 40, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[2399]);
  glDrawElements(GL_TRIANGLE_STRIP, 38, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[2439]);
  glDrawElements(GL_TRIANGLE_STRIP, 36, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[2477]);
  glDrawElements(GL_TRIANGLE_STRIP, 34, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[2513]);
  glDrawElements(GL_TRIANGLE_STRIP, 32, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[2547]);
  glDrawElements(GL_TRIANGLE_STRIP, 30, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[2579]);
  glDrawElements(GL_TRIANGLE_STRIP, 28, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[2609]);
  glDrawElements(GL_TRIANGLE_STRIP, 26, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[2637]);
  glDrawElements(GL_TRIANGLE_STRIP, 24, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[2663]);
  glDrawElements(GL_TRIANGLE_STRIP, 22, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[2687]);
  glDrawElements(GL_TRIANGLE_STRIP, 20, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[2709]);
  glDrawElements(GL_TRIANGLE_STRIP, 18, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[2729]);
  glDrawElements(GL_TRIANGLE_STRIP, 16, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[2747]);
  glDrawElements(GL_TRIANGLE_STRIP, 14, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[2763]);
  glDrawElements(GL_TRIANGLE_STRIP, 12, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[2777]);
  glDrawElements(GL_TRIANGLE_STRIP, 10, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[2789]);
  glDrawElements(GL_TRIANGLE_STRIP, 8, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[2799]);
  glDrawElements(GL_TRIANGLE_STRIP, 6, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[2807]);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[2813]);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[2816]);
  glDrawElements(GL_TRIANGLE_STRIP, 200, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[2819]);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[3019]);
  glDrawElements(GL_TRIANGLE_STRIP, 66, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[3022]);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[3088]);
  glDrawElements(GL_TRIANGLE_STRIP, 209, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[3091]);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[3300]);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[3303]);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[3306]);
  glDrawElements(GL_TRIANGLE_STRIP, 38, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[3309]);
  glDrawElements(GL_TRIANGLE_STRIP, 15, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[3347]);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[3362]);
  glDrawElements(GL_TRIANGLE_STRIP, 26, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[3365]);
  glDrawElements(GL_TRIANGLE_STRIP, 9, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[3391]);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[3400]);
  glDrawElements(GL_TRIANGLE_STRIP, 14, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[3403]);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[3417]);
  glDrawElements(GL_TRIANGLE_STRIP, 115, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[3420]);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[3535]);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[3538]);
  glDrawElements(GL_TRIANGLE_STRIP, 39, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[3541]);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[3580]);
  glDrawElements(GL_TRIANGLE_STRIP, 91, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[3583]);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[3674]);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[3677]);
  glDrawElements(GL_TRIANGLE_STRIP, 31, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[3680]);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[3711]);
  glDrawElements(GL_TRIANGLE_STRIP, 67, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[3714]);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[3781]);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[3784]);
  glDrawElements(GL_TRIANGLE_STRIP, 23, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[3787]);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[3810]);
  glDrawElements(GL_TRIANGLE_STRIP, 45, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[3813]);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[3858]);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[3861]);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[3864]);
  glDrawElements(GL_TRIANGLE_STRIP, 32, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[3867]);
  glDrawElements(GL_TRIANGLE_STRIP, 38, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[3899]);
  glDrawElements(GL_TRIANGLE_STRIP, 15, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[3937]);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[3952]);
  glDrawElements(GL_TRIANGLE_STRIP, 26, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[3955]);
  glDrawElements(GL_TRIANGLE_STRIP, 9, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[3981]);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[3990]);
  glDrawElements(GL_TRIANGLE_STRIP, 14, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[3993]);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[4007]);
  glDrawElements(GL_TRIANGLE_STRIP, 135, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[4010]);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[4145]);
  glDrawElements(GL_TRIANGLE_STRIP, 76, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[4148]);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[4224]);
  glDrawElements(GL_TRIANGLE_STRIP, 60, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[4227]);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[4287]);
  glDrawElements(GL_TRIANGLE_STRIP, 23, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[4290]);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[4313]);
  glDrawElements(GL_TRIANGLE_STRIP, 26, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[4316]);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[4342]);
  glDrawElements(GL_TRIANGLE_STRIP, 6, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[4345]);
  glDrawElements(GL_TRIANGLE_STRIP, 947, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[4351]);
  glDrawElements(GL_TRIANGLE_STRIP, 35, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[5298]);
  glDrawElements(GL_TRIANGLE_STRIP, 31, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[5333]);
  glDrawElements(GL_TRIANGLE_STRIP, 27, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[5364]);
  glDrawElements(GL_TRIANGLE_STRIP, 23, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[5391]);
  glDrawElements(GL_TRIANGLE_STRIP, 20, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[5414]);
  glDrawElements(GL_TRIANGLE_STRIP, 24, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[5434]);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[5458]);
  glDrawElements(GL_TRIANGLE_STRIP, 28, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[5461]);
  glDrawElements(GL_TRIANGLE_STRIP, 32, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[5489]);
  glDrawElements(GL_TRIANGLE_STRIP, 36, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[5521]);
  glDrawElements(GL_TRIANGLE_STRIP, 76, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[5557]);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[5633]);
  glDrawElements(GL_TRIANGLE_STRIP, 67, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[5636]);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[5703]);
  glDrawElements(GL_TRIANGLE_STRIP, 59, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[5706]);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[5765]);
  glDrawElements(GL_TRIANGLE_STRIP, 51, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[5768]);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[5819]);
  glDrawElements(GL_TRIANGLE_STRIP, 43, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[5822]);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[5865]);
  glDrawElements(GL_TRIANGLE_STRIP, 35, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[5868]);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[5903]);
  glDrawElements(GL_TRIANGLE_STRIP, 27, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[5906]);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[5933]);
  glDrawElements(GL_TRIANGLE_STRIP, 19, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[5936]);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[5955]);
  glDrawElements(GL_TRIANGLE_STRIP, 11, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[5958]);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[5969]);
  glDrawElements(GL_TRIANGLE_STRIP, 30, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[5972]);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[6002]);
  glDrawElements(GL_TRIANGLE_STRIP, 11, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[6005]);
  glDrawElements(GL_TRIANGLE_STRIP, 18, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[6016]);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[6034]);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[6037]);
  glDrawElements(GL_TRIANGLE_STRIP, 5, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[6040]);
  glDrawElements(GL_TRIANGLE_STRIP, 122, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[6045]);
  glDrawElements(GL_TRIANGLE_STRIP, 75, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[6167]);
  glDrawElements(GL_TRIANGLE_STRIP, 71, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[6242]);
  glDrawElements(GL_TRIANGLE_STRIP, 67, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[6313]);
  glDrawElements(GL_TRIANGLE_STRIP, 63, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[6380]);
  glDrawElements(GL_TRIANGLE_STRIP, 59, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[6443]);
  glDrawElements(GL_TRIANGLE_STRIP, 55, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[6502]);
  glDrawElements(GL_TRIANGLE_STRIP, 51, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[6557]);
  glDrawElements(GL_TRIANGLE_STRIP, 47, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[6608]);
  glDrawElements(GL_TRIANGLE_STRIP, 43, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[6655]);
  glDrawElements(GL_TRIANGLE_STRIP, 39, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[6698]);
  glDrawElements(GL_TRIANGLE_STRIP, 35, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[6737]);
  glDrawElements(GL_TRIANGLE_STRIP, 31, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[6772]);
  glDrawElements(GL_TRIANGLE_STRIP, 27, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[6803]);
  glDrawElements(GL_TRIANGLE_STRIP, 23, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[6830]);
  glDrawElements(GL_TRIANGLE_STRIP, 19, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[6853]);
  glDrawElements(GL_TRIANGLE_STRIP, 15, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[6872]);
  glDrawElements(GL_TRIANGLE_STRIP, 11, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[6887]);
  glDrawElements(GL_TRIANGLE_STRIP, 7, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[6898]);

  glDisableClientState(GL_VERTEX_ARRAY);	// disable vertex arrays
  glDisableClientState(GL_NORMAL_ARRAY);	// disable normal arrays
end;


{-------------------------------------------------------------------------------
  Create a display list for teapot
  Call creatTeapotDL() once to create a DL. createTeapotDL() will return a ID
  of display list. Use this ID to render later, glCallList(id).

  Since display lists are part of server state, the client state and commands
  cannot be stored in display list. Therefore, glEnableClientState,
  glDisableClientState, glVertexPointer, and glNormalPointer cannot be inside
  a display list. Above client calls must be reside outside of glNewList() and
  glEndList() function.
-------------------------------------------------------------------------------}
function CreateTeapotDL: GLuint;
var
  id: GLuint = 0;
begin
  // generate one display list
  id := glGenLists(1);

  if (id = 0) then begin    // failed to create a list, return 0
    Result := 0;
    exit;
  end;

  // bind vertex and normal pointers
  glEnableClientState(GL_NORMAL_ARRAY);
  glEnableClientState(GL_VERTEX_ARRAY);
  glNormalPointer(GL_FLOAT, 0, @TEAPOT_NORMALS);
  glVertexPointer(3, GL_FLOAT, 0, @TEAPOT_VERTICES);

  // store drawing function in the display list =============================
  glNewList(id, GL_COMPILE);

  // set specular and shiniess using glMaterial (gold-yellow)
  glMaterialf(GL_FRONT_AND_BACK, GL_SHININESS, Shininess); // range 0 ~ 128
  glMaterialfv(GL_FRONT_AND_BACK, GL_SPECULAR, SpecularColor);

  // set ambient and diffuse color using glColorMaterial (gold-yellow)
  glColorMaterial(GL_FRONT_AND_BACK, GL_AMBIENT_AND_DIFFUSE);
  glColor3fv(diffuseColor);

  // start to render polygons
  glDrawElements(GL_TRIANGLE_STRIP, 12, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[0]);
  glDrawElements(GL_TRIANGLE_STRIP, 78, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[12]);
  glDrawElements(GL_TRIANGLE_STRIP, 35, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[90]);
  glDrawElements(GL_TRIANGLE_STRIP, 70, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[125]);
  glDrawElements(GL_TRIANGLE_STRIP, 65, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[195]);
  glDrawElements(GL_TRIANGLE_STRIP, 37, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[260]);
  glDrawElements(GL_TRIANGLE_STRIP, 35, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[297]);
  glDrawElements(GL_TRIANGLE_STRIP, 32, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[332]);
  glDrawElements(GL_TRIANGLE_STRIP, 56, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[364]);
  glDrawElements(GL_TRIANGLE_STRIP, 45, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[420]);
  glDrawElements(GL_TRIANGLE_STRIP, 41, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[465]);
  glDrawElements(GL_TRIANGLE_STRIP, 37, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[506]);
  glDrawElements(GL_TRIANGLE_STRIP, 33, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[543]);
  glDrawElements(GL_TRIANGLE_STRIP, 29, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[576]);
  glDrawElements(GL_TRIANGLE_STRIP, 25, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[605]);
  glDrawElements(GL_TRIANGLE_STRIP, 21, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[630]);
  glDrawElements(GL_TRIANGLE_STRIP, 17, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[651]);
  glDrawElements(GL_TRIANGLE_STRIP, 13, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[668]);
  glDrawElements(GL_TRIANGLE_STRIP, 9, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[681]);
  glDrawElements(GL_TRIANGLE_STRIP, 27, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[690]);
  glDrawElements(GL_TRIANGLE_STRIP, 16, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[717]);
  glDrawElements(GL_TRIANGLE_STRIP, 22, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[733]);
  glDrawElements(GL_TRIANGLE_STRIP, 50, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[755]);
  glDrawElements(GL_TRIANGLE_STRIP, 42, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[805]);
  glDrawElements(GL_TRIANGLE_STRIP, 43, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[847]);
  glDrawElements(GL_TRIANGLE_STRIP, 4, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[890]);
  glDrawElements(GL_TRIANGLE_STRIP, 143, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[894]);
  glDrawElements(GL_TRIANGLE_STRIP, 234, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[1037]);
  glDrawElements(GL_TRIANGLE_STRIP, 224, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[1271]);
  glDrawElements(GL_TRIANGLE_STRIP, 71, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[1495]);
  glDrawElements(GL_TRIANGLE_STRIP, 69, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[1566]);
  glDrawElements(GL_TRIANGLE_STRIP, 67, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[1635]);
  glDrawElements(GL_TRIANGLE_STRIP, 65, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[1702]);
  glDrawElements(GL_TRIANGLE_STRIP, 63, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[1767]);
  glDrawElements(GL_TRIANGLE_STRIP, 61, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[1830]);
  glDrawElements(GL_TRIANGLE_STRIP, 59, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[1891]);
  glDrawElements(GL_TRIANGLE_STRIP, 57, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[1950]);
  glDrawElements(GL_TRIANGLE_STRIP, 55, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[2007]);
  glDrawElements(GL_TRIANGLE_STRIP, 53, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[2062]);
  glDrawElements(GL_TRIANGLE_STRIP, 51, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[2115]);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[2166]);
  glDrawElements(GL_TRIANGLE_STRIP, 50, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[2169]);
  glDrawElements(GL_TRIANGLE_STRIP, 48, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[2219]);
  glDrawElements(GL_TRIANGLE_STRIP, 46, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[2267]);
  glDrawElements(GL_TRIANGLE_STRIP, 44, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[2313]);
  glDrawElements(GL_TRIANGLE_STRIP, 42, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[2357]);
  glDrawElements(GL_TRIANGLE_STRIP, 40, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[2399]);
  glDrawElements(GL_TRIANGLE_STRIP, 38, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[2439]);
  glDrawElements(GL_TRIANGLE_STRIP, 36, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[2477]);
  glDrawElements(GL_TRIANGLE_STRIP, 34, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[2513]);
  glDrawElements(GL_TRIANGLE_STRIP, 32, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[2547]);
  glDrawElements(GL_TRIANGLE_STRIP, 30, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[2579]);
  glDrawElements(GL_TRIANGLE_STRIP, 28, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[2609]);
  glDrawElements(GL_TRIANGLE_STRIP, 26, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[2637]);
  glDrawElements(GL_TRIANGLE_STRIP, 24, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[2663]);
  glDrawElements(GL_TRIANGLE_STRIP, 22, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[2687]);
  glDrawElements(GL_TRIANGLE_STRIP, 20, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[2709]);
  glDrawElements(GL_TRIANGLE_STRIP, 18, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[2729]);
  glDrawElements(GL_TRIANGLE_STRIP, 16, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[2747]);
  glDrawElements(GL_TRIANGLE_STRIP, 14, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[2763]);
  glDrawElements(GL_TRIANGLE_STRIP, 12, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[2777]);
  glDrawElements(GL_TRIANGLE_STRIP, 10, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[2789]);
  glDrawElements(GL_TRIANGLE_STRIP, 8, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[2799]);
  glDrawElements(GL_TRIANGLE_STRIP, 6, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[2807]);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[2813]);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[2816]);
  glDrawElements(GL_TRIANGLE_STRIP, 200, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[2819]);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[3019]);
  glDrawElements(GL_TRIANGLE_STRIP, 66, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[3022]);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[3088]);
  glDrawElements(GL_TRIANGLE_STRIP, 209, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[3091]);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[3300]);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[3303]);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[3306]);
  glDrawElements(GL_TRIANGLE_STRIP, 38, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[3309]);
  glDrawElements(GL_TRIANGLE_STRIP, 15, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[3347]);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[3362]);
  glDrawElements(GL_TRIANGLE_STRIP, 26, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[3365]);
  glDrawElements(GL_TRIANGLE_STRIP, 9, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[3391]);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[3400]);
  glDrawElements(GL_TRIANGLE_STRIP, 14, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[3403]);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[3417]);
  glDrawElements(GL_TRIANGLE_STRIP, 115, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[3420]);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[3535]);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[3538]);
  glDrawElements(GL_TRIANGLE_STRIP, 39, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[3541]);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[3580]);
  glDrawElements(GL_TRIANGLE_STRIP, 91, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[3583]);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[3674]);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[3677]);
  glDrawElements(GL_TRIANGLE_STRIP, 31, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[3680]);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[3711]);
  glDrawElements(GL_TRIANGLE_STRIP, 67, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[3714]);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[3781]);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[3784]);
  glDrawElements(GL_TRIANGLE_STRIP, 23, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[3787]);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[3810]);
  glDrawElements(GL_TRIANGLE_STRIP, 45, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[3813]);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[3858]);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[3861]);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[3864]);
  glDrawElements(GL_TRIANGLE_STRIP, 32, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[3867]);
  glDrawElements(GL_TRIANGLE_STRIP, 38, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[3899]);
  glDrawElements(GL_TRIANGLE_STRIP, 15, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[3937]);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[3952]);
  glDrawElements(GL_TRIANGLE_STRIP, 26, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[3955]);
  glDrawElements(GL_TRIANGLE_STRIP, 9, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[3981]);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[3990]);
  glDrawElements(GL_TRIANGLE_STRIP, 14, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[3993]);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[4007]);
  glDrawElements(GL_TRIANGLE_STRIP, 135, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[4010]);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[4145]);
  glDrawElements(GL_TRIANGLE_STRIP, 76, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[4148]);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[4224]);
  glDrawElements(GL_TRIANGLE_STRIP, 60, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[4227]);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[4287]);
  glDrawElements(GL_TRIANGLE_STRIP, 23, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[4290]);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[4313]);
  glDrawElements(GL_TRIANGLE_STRIP, 26, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[4316]);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[4342]);
  glDrawElements(GL_TRIANGLE_STRIP, 6, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[4345]);
  glDrawElements(GL_TRIANGLE_STRIP, 947, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[4351]);
  glDrawElements(GL_TRIANGLE_STRIP, 35, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[5298]);
  glDrawElements(GL_TRIANGLE_STRIP, 31, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[5333]);
  glDrawElements(GL_TRIANGLE_STRIP, 27, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[5364]);
  glDrawElements(GL_TRIANGLE_STRIP, 23, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[5391]);
  glDrawElements(GL_TRIANGLE_STRIP, 20, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[5414]);
  glDrawElements(GL_TRIANGLE_STRIP, 24, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[5434]);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[5458]);
  glDrawElements(GL_TRIANGLE_STRIP, 28, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[5461]);
  glDrawElements(GL_TRIANGLE_STRIP, 32, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[5489]);
  glDrawElements(GL_TRIANGLE_STRIP, 36, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[5521]);
  glDrawElements(GL_TRIANGLE_STRIP, 76, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[5557]);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[5633]);
  glDrawElements(GL_TRIANGLE_STRIP, 67, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[5636]);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[5703]);
  glDrawElements(GL_TRIANGLE_STRIP, 59, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[5706]);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[5765]);
  glDrawElements(GL_TRIANGLE_STRIP, 51, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[5768]);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[5819]);
  glDrawElements(GL_TRIANGLE_STRIP, 43, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[5822]);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[5865]);
  glDrawElements(GL_TRIANGLE_STRIP, 35, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[5868]);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[5903]);
  glDrawElements(GL_TRIANGLE_STRIP, 27, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[5906]);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[5933]);
  glDrawElements(GL_TRIANGLE_STRIP, 19, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[5936]);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[5955]);
  glDrawElements(GL_TRIANGLE_STRIP, 11, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[5958]);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[5969]);
  glDrawElements(GL_TRIANGLE_STRIP, 30, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[5972]);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[6002]);
  glDrawElements(GL_TRIANGLE_STRIP, 11, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[6005]);
  glDrawElements(GL_TRIANGLE_STRIP, 18, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[6016]);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[6034]);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[6037]);
  glDrawElements(GL_TRIANGLE_STRIP, 5, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[6040]);
  glDrawElements(GL_TRIANGLE_STRIP, 122, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[6045]);
  glDrawElements(GL_TRIANGLE_STRIP, 75, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[6167]);
  glDrawElements(GL_TRIANGLE_STRIP, 71, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[6242]);
  glDrawElements(GL_TRIANGLE_STRIP, 67, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[6313]);
  glDrawElements(GL_TRIANGLE_STRIP, 63, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[6380]);
  glDrawElements(GL_TRIANGLE_STRIP, 59, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[6443]);
  glDrawElements(GL_TRIANGLE_STRIP, 55, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[6502]);
  glDrawElements(GL_TRIANGLE_STRIP, 51, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[6557]);
  glDrawElements(GL_TRIANGLE_STRIP, 47, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[6608]);
  glDrawElements(GL_TRIANGLE_STRIP, 43, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[6655]);
  glDrawElements(GL_TRIANGLE_STRIP, 39, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[6698]);
  glDrawElements(GL_TRIANGLE_STRIP, 35, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[6737]);
  glDrawElements(GL_TRIANGLE_STRIP, 31, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[6772]);
  glDrawElements(GL_TRIANGLE_STRIP, 27, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[6803]);
  glDrawElements(GL_TRIANGLE_STRIP, 23, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[6830]);
  glDrawElements(GL_TRIANGLE_STRIP, 19, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[6853]);
  glDrawElements(GL_TRIANGLE_STRIP, 15, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[6872]);
  glDrawElements(GL_TRIANGLE_STRIP, 11, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[6887]);
  glDrawElements(GL_TRIANGLE_STRIP, 7, GL_UNSIGNED_SHORT, @TEAPOT_INDICES[6898]);

  glEndList();	//=========================================================

  glDisableClientState(GL_VERTEX_ARRAY);	// disable vertex arrays
  glDisableClientState(GL_NORMAL_ARRAY);	// disable normal arrays

  Result := id;  // use this for drawing
end;


{-------------------------------------------------------------------------------
  Draw teapot using only offset instead of absolute pointers.
  The caller must bind buffer ids and set the starting offset before call this
  functions. (glBindBufferARB, glVertexPointer, glNormalPointer, glIndexPointer)
-------------------------------------------------------------------------------}
procedure DrawTeapotVBO;
begin
  // set specular and shiniess using glMaterial (gold-yellow)
  glMaterialf(GL_FRONT_AND_BACK, GL_SHININESS, Shininess); // range 0 ~ 128
  glMaterialfv(GL_FRONT_AND_BACK, GL_SPECULAR, SpecularColor);

  // set ambient and diffuse color using glColorMaterial (gold-yellow)
  glColorMaterial(GL_FRONT_AND_BACK, GL_AMBIENT_AND_DIFFUSE);
  glColor3fv(DiffuseColor);

  // start to render polygons
  glEnableClientState(GL_NORMAL_ARRAY);
  glEnableClientState(GL_VERTEX_ARRAY);
                                       {
  // use only offset here instead of absolute pointer addresses
  glDrawElements(GL_TRIANGLE_STRIP, 12, GL_UNSIGNED_SHORT, (GLushort*)0+0);
  glDrawElements(GL_TRIANGLE_STRIP, 78, GL_UNSIGNED_SHORT, (GLushort*)0+12);
  glDrawElements(GL_TRIANGLE_STRIP, 35, GL_UNSIGNED_SHORT, (GLushort*)0+90);
  glDrawElements(GL_TRIANGLE_STRIP, 70, GL_UNSIGNED_SHORT, (GLushort*)0+125);
  glDrawElements(GL_TRIANGLE_STRIP, 65, GL_UNSIGNED_SHORT, (GLushort*)0+195);
  glDrawElements(GL_TRIANGLE_STRIP, 37, GL_UNSIGNED_SHORT, (GLushort*)0+260);
  glDrawElements(GL_TRIANGLE_STRIP, 35, GL_UNSIGNED_SHORT, (GLushort*)0+297);
  glDrawElements(GL_TRIANGLE_STRIP, 32, GL_UNSIGNED_SHORT, (GLushort*)0+332);
  glDrawElements(GL_TRIANGLE_STRIP, 56, GL_UNSIGNED_SHORT, (GLushort*)0+364);
  glDrawElements(GL_TRIANGLE_STRIP, 45, GL_UNSIGNED_SHORT, (GLushort*)0+420);
  glDrawElements(GL_TRIANGLE_STRIP, 41, GL_UNSIGNED_SHORT, (GLushort*)0+465);
  glDrawElements(GL_TRIANGLE_STRIP, 37, GL_UNSIGNED_SHORT, (GLushort*)0+506);
  glDrawElements(GL_TRIANGLE_STRIP, 33, GL_UNSIGNED_SHORT, (GLushort*)0+543);
  glDrawElements(GL_TRIANGLE_STRIP, 29, GL_UNSIGNED_SHORT, (GLushort*)0+576);
  glDrawElements(GL_TRIANGLE_STRIP, 25, GL_UNSIGNED_SHORT, (GLushort*)0+605);
  glDrawElements(GL_TRIANGLE_STRIP, 21, GL_UNSIGNED_SHORT, (GLushort*)0+630);
  glDrawElements(GL_TRIANGLE_STRIP, 17, GL_UNSIGNED_SHORT, (GLushort*)0+651);
  glDrawElements(GL_TRIANGLE_STRIP, 13, GL_UNSIGNED_SHORT, (GLushort*)0+668);
  glDrawElements(GL_TRIANGLE_STRIP, 9, GL_UNSIGNED_SHORT, (GLushort*)0+681);
  glDrawElements(GL_TRIANGLE_STRIP, 27, GL_UNSIGNED_SHORT, (GLushort*)0+690);
  glDrawElements(GL_TRIANGLE_STRIP, 16, GL_UNSIGNED_SHORT, (GLushort*)0+717);
  glDrawElements(GL_TRIANGLE_STRIP, 22, GL_UNSIGNED_SHORT, (GLushort*)0+733);
  glDrawElements(GL_TRIANGLE_STRIP, 50, GL_UNSIGNED_SHORT, (GLushort*)0+755);
  glDrawElements(GL_TRIANGLE_STRIP, 42, GL_UNSIGNED_SHORT, (GLushort*)0+805);
  glDrawElements(GL_TRIANGLE_STRIP, 43, GL_UNSIGNED_SHORT, (GLushort*)0+847);
  glDrawElements(GL_TRIANGLE_STRIP, 4, GL_UNSIGNED_SHORT, (GLushort*)0+890);
  glDrawElements(GL_TRIANGLE_STRIP, 143, GL_UNSIGNED_SHORT, (GLushort*)0+894);
  glDrawElements(GL_TRIANGLE_STRIP, 234, GL_UNSIGNED_SHORT, (GLushort*)0+1037);
  glDrawElements(GL_TRIANGLE_STRIP, 224, GL_UNSIGNED_SHORT, (GLushort*)0+1271);
  glDrawElements(GL_TRIANGLE_STRIP, 71, GL_UNSIGNED_SHORT, (GLushort*)0+1495);
  glDrawElements(GL_TRIANGLE_STRIP, 69, GL_UNSIGNED_SHORT, (GLushort*)0+1566);
  glDrawElements(GL_TRIANGLE_STRIP, 67, GL_UNSIGNED_SHORT, (GLushort*)0+1635);
  glDrawElements(GL_TRIANGLE_STRIP, 65, GL_UNSIGNED_SHORT, (GLushort*)0+1702);
  glDrawElements(GL_TRIANGLE_STRIP, 63, GL_UNSIGNED_SHORT, (GLushort*)0+1767);
  glDrawElements(GL_TRIANGLE_STRIP, 61, GL_UNSIGNED_SHORT, (GLushort*)0+1830);
  glDrawElements(GL_TRIANGLE_STRIP, 59, GL_UNSIGNED_SHORT, (GLushort*)0+1891);
  glDrawElements(GL_TRIANGLE_STRIP, 57, GL_UNSIGNED_SHORT, (GLushort*)0+1950);
  glDrawElements(GL_TRIANGLE_STRIP, 55, GL_UNSIGNED_SHORT, (GLushort*)0+2007);
  glDrawElements(GL_TRIANGLE_STRIP, 53, GL_UNSIGNED_SHORT, (GLushort*)0+2062);
  glDrawElements(GL_TRIANGLE_STRIP, 51, GL_UNSIGNED_SHORT, (GLushort*)0+2115);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, (GLushort*)0+2166);
  glDrawElements(GL_TRIANGLE_STRIP, 50, GL_UNSIGNED_SHORT, (GLushort*)0+2169);
  glDrawElements(GL_TRIANGLE_STRIP, 48, GL_UNSIGNED_SHORT, (GLushort*)0+2219);
  glDrawElements(GL_TRIANGLE_STRIP, 46, GL_UNSIGNED_SHORT, (GLushort*)0+2267);
  glDrawElements(GL_TRIANGLE_STRIP, 44, GL_UNSIGNED_SHORT, (GLushort*)0+2313);
  glDrawElements(GL_TRIANGLE_STRIP, 42, GL_UNSIGNED_SHORT, (GLushort*)0+2357);
  glDrawElements(GL_TRIANGLE_STRIP, 40, GL_UNSIGNED_SHORT, (GLushort*)0+2399);
  glDrawElements(GL_TRIANGLE_STRIP, 38, GL_UNSIGNED_SHORT, (GLushort*)0+2439);
  glDrawElements(GL_TRIANGLE_STRIP, 36, GL_UNSIGNED_SHORT, (GLushort*)0+2477);
  glDrawElements(GL_TRIANGLE_STRIP, 34, GL_UNSIGNED_SHORT, (GLushort*)0+2513);
  glDrawElements(GL_TRIANGLE_STRIP, 32, GL_UNSIGNED_SHORT, (GLushort*)0+2547);
  glDrawElements(GL_TRIANGLE_STRIP, 30, GL_UNSIGNED_SHORT, (GLushort*)0+2579);
  glDrawElements(GL_TRIANGLE_STRIP, 28, GL_UNSIGNED_SHORT, (GLushort*)0+2609);
  glDrawElements(GL_TRIANGLE_STRIP, 26, GL_UNSIGNED_SHORT, (GLushort*)0+2637);
  glDrawElements(GL_TRIANGLE_STRIP, 24, GL_UNSIGNED_SHORT, (GLushort*)0+2663);
  glDrawElements(GL_TRIANGLE_STRIP, 22, GL_UNSIGNED_SHORT, (GLushort*)0+2687);
  glDrawElements(GL_TRIANGLE_STRIP, 20, GL_UNSIGNED_SHORT, (GLushort*)0+2709);
  glDrawElements(GL_TRIANGLE_STRIP, 18, GL_UNSIGNED_SHORT, (GLushort*)0+2729);
  glDrawElements(GL_TRIANGLE_STRIP, 16, GL_UNSIGNED_SHORT, (GLushort*)0+2747);
  glDrawElements(GL_TRIANGLE_STRIP, 14, GL_UNSIGNED_SHORT, (GLushort*)0+2763);
  glDrawElements(GL_TRIANGLE_STRIP, 12, GL_UNSIGNED_SHORT, (GLushort*)0+2777);
  glDrawElements(GL_TRIANGLE_STRIP, 10, GL_UNSIGNED_SHORT, (GLushort*)0+2789);
  glDrawElements(GL_TRIANGLE_STRIP, 8, GL_UNSIGNED_SHORT, (GLushort*)0+2799);
  glDrawElements(GL_TRIANGLE_STRIP, 6, GL_UNSIGNED_SHORT, (GLushort*)0+2807);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, (GLushort*)0+2813);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, (GLushort*)0+2816);
  glDrawElements(GL_TRIANGLE_STRIP, 200, GL_UNSIGNED_SHORT, (GLushort*)0+2819);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, (GLushort*)0+3019);
  glDrawElements(GL_TRIANGLE_STRIP, 66, GL_UNSIGNED_SHORT, (GLushort*)0+3022);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, (GLushort*)0+3088);
  glDrawElements(GL_TRIANGLE_STRIP, 209, GL_UNSIGNED_SHORT, (GLushort*)0+3091);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, (GLushort*)0+3300);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, (GLushort*)0+3303);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, (GLushort*)0+3306);
  glDrawElements(GL_TRIANGLE_STRIP, 38, GL_UNSIGNED_SHORT, (GLushort*)0+3309);
  glDrawElements(GL_TRIANGLE_STRIP, 15, GL_UNSIGNED_SHORT, (GLushort*)0+3347);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, (GLushort*)0+3362);
  glDrawElements(GL_TRIANGLE_STRIP, 26, GL_UNSIGNED_SHORT, (GLushort*)0+3365);
  glDrawElements(GL_TRIANGLE_STRIP, 9, GL_UNSIGNED_SHORT, (GLushort*)0+3391);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, (GLushort*)0+3400);
  glDrawElements(GL_TRIANGLE_STRIP, 14, GL_UNSIGNED_SHORT, (GLushort*)0+3403);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, (GLushort*)0+3417);
  glDrawElements(GL_TRIANGLE_STRIP, 115, GL_UNSIGNED_SHORT, (GLushort*)0+3420);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, (GLushort*)0+3535);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, (GLushort*)0+3538);
  glDrawElements(GL_TRIANGLE_STRIP, 39, GL_UNSIGNED_SHORT, (GLushort*)0+3541);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, (GLushort*)0+3580);
  glDrawElements(GL_TRIANGLE_STRIP, 91, GL_UNSIGNED_SHORT, (GLushort*)0+3583);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, (GLushort*)0+3674);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, (GLushort*)0+3677);
  glDrawElements(GL_TRIANGLE_STRIP, 31, GL_UNSIGNED_SHORT, (GLushort*)0+3680);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, (GLushort*)0+3711);
  glDrawElements(GL_TRIANGLE_STRIP, 67, GL_UNSIGNED_SHORT, (GLushort*)0+3714);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, (GLushort*)0+3781);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, (GLushort*)0+3784);
  glDrawElements(GL_TRIANGLE_STRIP, 23, GL_UNSIGNED_SHORT, (GLushort*)0+3787);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, (GLushort*)0+3810);
  glDrawElements(GL_TRIANGLE_STRIP, 45, GL_UNSIGNED_SHORT, (GLushort*)0+3813);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, (GLushort*)0+3858);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, (GLushort*)0+3861);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, (GLushort*)0+3864);
  glDrawElements(GL_TRIANGLE_STRIP, 32, GL_UNSIGNED_SHORT, (GLushort*)0+3867);
  glDrawElements(GL_TRIANGLE_STRIP, 38, GL_UNSIGNED_SHORT, (GLushort*)0+3899);
  glDrawElements(GL_TRIANGLE_STRIP, 15, GL_UNSIGNED_SHORT, (GLushort*)0+3937);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, (GLushort*)0+3952);
  glDrawElements(GL_TRIANGLE_STRIP, 26, GL_UNSIGNED_SHORT, (GLushort*)0+3955);
  glDrawElements(GL_TRIANGLE_STRIP, 9, GL_UNSIGNED_SHORT, (GLushort*)0+3981);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, (GLushort*)0+3990);
  glDrawElements(GL_TRIANGLE_STRIP, 14, GL_UNSIGNED_SHORT, (GLushort*)0+3993);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, (GLushort*)0+4007);
  glDrawElements(GL_TRIANGLE_STRIP, 135, GL_UNSIGNED_SHORT, (GLushort*)0+4010);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, (GLushort*)0+4145);
  glDrawElements(GL_TRIANGLE_STRIP, 76, GL_UNSIGNED_SHORT, (GLushort*)0+4148);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, (GLushort*)0+4224);
  glDrawElements(GL_TRIANGLE_STRIP, 60, GL_UNSIGNED_SHORT, (GLushort*)0+4227);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, (GLushort*)0+4287);
  glDrawElements(GL_TRIANGLE_STRIP, 23, GL_UNSIGNED_SHORT, (GLushort*)0+4290);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, (GLushort*)0+4313);
  glDrawElements(GL_TRIANGLE_STRIP, 26, GL_UNSIGNED_SHORT, (GLushort*)0+4316);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, (GLushort*)0+4342);
  glDrawElements(GL_TRIANGLE_STRIP, 6, GL_UNSIGNED_SHORT, (GLushort*)0+4345);
  glDrawElements(GL_TRIANGLE_STRIP, 947, GL_UNSIGNED_SHORT, (GLushort*)0+4351);
  glDrawElements(GL_TRIANGLE_STRIP, 35, GL_UNSIGNED_SHORT, (GLushort*)0+5298);
  glDrawElements(GL_TRIANGLE_STRIP, 31, GL_UNSIGNED_SHORT, (GLushort*)0+5333);
  glDrawElements(GL_TRIANGLE_STRIP, 27, GL_UNSIGNED_SHORT, (GLushort*)0+5364);
  glDrawElements(GL_TRIANGLE_STRIP, 23, GL_UNSIGNED_SHORT, (GLushort*)0+5391);
  glDrawElements(GL_TRIANGLE_STRIP, 20, GL_UNSIGNED_SHORT, (GLushort*)0+5414);
  glDrawElements(GL_TRIANGLE_STRIP, 24, GL_UNSIGNED_SHORT, (GLushort*)0+5434);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, (GLushort*)0+5458);
  glDrawElements(GL_TRIANGLE_STRIP, 28, GL_UNSIGNED_SHORT, (GLushort*)0+5461);
  glDrawElements(GL_TRIANGLE_STRIP, 32, GL_UNSIGNED_SHORT, (GLushort*)0+5489);
  glDrawElements(GL_TRIANGLE_STRIP, 36, GL_UNSIGNED_SHORT, (GLushort*)0+5521);
  glDrawElements(GL_TRIANGLE_STRIP, 76, GL_UNSIGNED_SHORT, (GLushort*)0+5557);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, (GLushort*)0+5633);
  glDrawElements(GL_TRIANGLE_STRIP, 67, GL_UNSIGNED_SHORT, (GLushort*)0+5636);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, (GLushort*)0+5703);
  glDrawElements(GL_TRIANGLE_STRIP, 59, GL_UNSIGNED_SHORT, (GLushort*)0+5706);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, (GLushort*)0+5765);
  glDrawElements(GL_TRIANGLE_STRIP, 51, GL_UNSIGNED_SHORT, (GLushort*)0+5768);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, (GLushort*)0+5819);
  glDrawElements(GL_TRIANGLE_STRIP, 43, GL_UNSIGNED_SHORT, (GLushort*)0+5822);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, (GLushort*)0+5865);
  glDrawElements(GL_TRIANGLE_STRIP, 35, GL_UNSIGNED_SHORT, (GLushort*)0+5868);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, (GLushort*)0+5903);
  glDrawElements(GL_TRIANGLE_STRIP, 27, GL_UNSIGNED_SHORT, (GLushort*)0+5906);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, (GLushort*)0+5933);
  glDrawElements(GL_TRIANGLE_STRIP, 19, GL_UNSIGNED_SHORT, (GLushort*)0+5936);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, (GLushort*)0+5955);
  glDrawElements(GL_TRIANGLE_STRIP, 11, GL_UNSIGNED_SHORT, (GLushort*)0+5958);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, (GLushort*)0+5969);
  glDrawElements(GL_TRIANGLE_STRIP, 30, GL_UNSIGNED_SHORT, (GLushort*)0+5972);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, (GLushort*)0+6002);
  glDrawElements(GL_TRIANGLE_STRIP, 11, GL_UNSIGNED_SHORT, (GLushort*)0+6005);
  glDrawElements(GL_TRIANGLE_STRIP, 18, GL_UNSIGNED_SHORT, (GLushort*)0+6016);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, (GLushort*)0+6034);
  glDrawElements(GL_TRIANGLES, 3, GL_UNSIGNED_SHORT, (GLushort*)0+6037);
  glDrawElements(GL_TRIANGLE_STRIP, 5, GL_UNSIGNED_SHORT, (GLushort*)0+6040);
  glDrawElements(GL_TRIANGLE_STRIP, 122, GL_UNSIGNED_SHORT, (GLushort*)0+6045);
  glDrawElements(GL_TRIANGLE_STRIP, 75, GL_UNSIGNED_SHORT, (GLushort*)0+6167);
  glDrawElements(GL_TRIANGLE_STRIP, 71, GL_UNSIGNED_SHORT, (GLushort*)0+6242);
  glDrawElements(GL_TRIANGLE_STRIP, 67, GL_UNSIGNED_SHORT, (GLushort*)0+6313);
  glDrawElements(GL_TRIANGLE_STRIP, 63, GL_UNSIGNED_SHORT, (GLushort*)0+6380);
  glDrawElements(GL_TRIANGLE_STRIP, 59, GL_UNSIGNED_SHORT, (GLushort*)0+6443);
  glDrawElements(GL_TRIANGLE_STRIP, 55, GL_UNSIGNED_SHORT, (GLushort*)0+6502);
  glDrawElements(GL_TRIANGLE_STRIP, 51, GL_UNSIGNED_SHORT, (GLushort*)0+6557);
  glDrawElements(GL_TRIANGLE_STRIP, 47, GL_UNSIGNED_SHORT, (GLushort*)0+6608);
  glDrawElements(GL_TRIANGLE_STRIP, 43, GL_UNSIGNED_SHORT, (GLushort*)0+6655);
  glDrawElements(GL_TRIANGLE_STRIP, 39, GL_UNSIGNED_SHORT, (GLushort*)0+6698);
  glDrawElements(GL_TRIANGLE_STRIP, 35, GL_UNSIGNED_SHORT, (GLushort*)0+6737);
  glDrawElements(GL_TRIANGLE_STRIP, 31, GL_UNSIGNED_SHORT, (GLushort*)0+6772);
  glDrawElements(GL_TRIANGLE_STRIP, 27, GL_UNSIGNED_SHORT, (GLushort*)0+6803);
  glDrawElements(GL_TRIANGLE_STRIP, 23, GL_UNSIGNED_SHORT, (GLushort*)0+6830);
  glDrawElements(GL_TRIANGLE_STRIP, 19, GL_UNSIGNED_SHORT, (GLushort*)0+6853);
  glDrawElements(GL_TRIANGLE_STRIP, 15, GL_UNSIGNED_SHORT, (GLushort*)0+6872);
  glDrawElements(GL_TRIANGLE_STRIP, 11, GL_UNSIGNED_SHORT, (GLushort*)0+6887);
  glDrawElements(GL_TRIANGLE_STRIP, 7, GL_UNSIGNED_SHORT, (GLushort*)0+6898);

  glDisableClientState(GL_VERTEX_ARRAY);	// disable vertex arrays
  glDisableClientState(GL_NORMAL_ARRAY);	// disable normal arrays
  }
end;

end.

